# Print-ready lens: simulation-optimised shells + transducer interface.
# Generated by tools/merge_transducer_interface.py -- regenerate rather than edit.
# 
# lens source     : Z:\cones-and-domes-paper\solidworks_export\bowl_amplitude_multispline_stitched.mat
# interface part  : Z:/JAXisymmetric/results/JAXdomeV2.SLDPRT  (trimmed above y = 24.000 mm)
# lens wall       : 1.0000 mm
# skirt wall      : 1.500 mm, y 23.00-28.50 mm
# skirt vents     : 8 x dia 3.00 mm at r = 38.504 mm
# cavity vents    : 18 holes in 3 ring(s), dia 2.00 mm
# aperture clear  : +2.073 mm outside r = 32.0 mm
# axis            : global Y; y measured from the simulation grid origin,
#                   so y = 24 mm is the transducer source plane
# units           : metres (the SOLIDWORKS API is always SI)

$ErrorActionPreference = 'Stop'

# SOLIDWORKS ships these interop assemblies with every install. They are
# needed because the SOLIDWORKS API takes double[] arrays that late-bound
# scripting hosts cannot construct.
$redist = 'C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS\api\redist'
$dlls = @('SolidWorks.Interop.sldworks.dll', 'SolidWorks.Interop.swconst.dll') |
    ForEach-Object { Join-Path $redist $_ }
foreach ($d in $dlls) {
    if (-not (Test-Path $d)) { throw "interop assembly not found: $d" }
    [Reflection.Assembly]::LoadFrom($d) | Out-Null
}
# The assemblies live outside the probing path, so answer resolve requests.
[AppDomain]::CurrentDomain.add_AssemblyResolve({
    param($s, $e)
    $n = $e.Name.Split(',')[0]
    $hit = $dlls | Where-Object { [IO.Path]::GetFileNameWithoutExtension($_) -eq $n }
    if ($hit) { return [Reflection.Assembly]::LoadFrom($hit) }
    return $null
})

$cs = @'
using System;
using System.Text;
using SolidWorks.Interop.sldworks;

public static class MultiSplineBuild
{
    static StringBuilder log = new StringBuilder();
    static void Log(string s) { log.AppendLine(s); Console.WriteLine(s); }

    // InsertSketch toggles, and some templates open a sketch on creation, so
    // close any active sketch before opening ours.
    static bool OpenSketch(IModelDoc2 model, string plane, string tag)
    {
        ISketchManager sk = model.SketchManager;
        if (sk.ActiveSketch != null) sk.InsertSketch(true);
        model.ClearSelection2(true);
        bool ok = model.Extension.SelectByID2(plane, "PLANE", 0, 0, 0, false, 0, null, 0);
        if (!ok)
        {
            Log("  note: no plane named \"" + plane + "\"; using the first reference plane");
            IFeature f = (IFeature)model.FirstFeature();
            while (f != null)
            {
                if (f.GetTypeName2() == "RefPlane") { ok = f.Select2(false, 0); break; }
                f = (IFeature)f.GetNextFeature();
            }
        }
        if (!ok) { Log("ERROR: could not select a sketch plane for " + tag); return false; }
        sk.InsertSketch(true);
        if (sk.ActiveSketch == null) { Log("ERROR: no sketch opened for " + tag); return false; }
        return true;
    }

    static bool CloseAndRevolve(IModelDoc2 model, string tag, string name, double angle,
                                bool merge)
    {
        model.ClearSelection2(true);
        model.SketchManager.InsertSketch(true);
        IFeature skFeat = (IFeature)model.FeatureByPositionReverse(0);
        if (skFeat == null) { Log("ERROR: sketch feature not found for " + tag); return false; }
        skFeat.Name = "MS_Profile_" + name;
        model.ClearSelection2(true);
        skFeat.Select2(false, 0);
        IFeature rev = model.FeatureManager.FeatureRevolve2(
            true, true, false, false, false, false, 0, 0, angle, 0,
            false, false, 0, 0, 0, 0, 0, merge, true, true);
        if (rev == null) { Log("ERROR: revolve failed for " + tag); return false; }
        rev.Name = "MS_Revolve_" + name;
        Log("  " + tag + " -> " + rev.Name);
        return true;
    }

    // One explicit union at the end, rather than letting each revolve merge as it
    // goes. Incremental merging is order- and coincidence-sensitive: unioning a
    // body that carries a void into bodies already present can fail outright,
    // and which orientation happens to survive is luck.
    static void CombineAll(IModelDoc2 model)
    {
        object bodiesObj = ((IPartDoc)model).GetBodies2(0, true);
        object[] bodies = bodiesObj as object[];
        if (bodies == null || bodies.Length < 2)
        {
            Log("combine: " + (bodies == null ? 0 : bodies.Length) + " body, nothing to do");
            return;
        }
        // InsertCombineFeature is typed against Body2, not IBody2, and wants a
        // typed Body2[] for the tools -- an object[] marshals as VARIANTs and is
        // rejected.
        Body2 main = (Body2)bodies[0];
        Body2[] tools = new Body2[bodies.Length - 1];
        for (int i = 1; i < bodies.Length; i++) tools[i - 1] = (Body2)bodies[i];
        model.ClearSelection2(true);
        object c = null;
        try { c = model.FeatureManager.InsertCombineFeature(15903, main, tools); }
        catch (Exception e) { Log("combine threw: " + e.Message); }
        if (c == null)
        {
            // Fall back to the selection-driven route: select every body and let
            // SOLIDWORKS pick the main one itself.
            model.ClearSelection2(true);
            for (int i = 0; i < bodies.Length; i++) ((Body2)bodies[i]).Select2(true, null);
            try { c = model.FeatureManager.InsertCombineFeature(15903, null, null); }
            catch (Exception e) { Log("combine (selection) threw: " + e.Message); }
        }
        Log("combine-add of " + bodies.Length + " bodies: " + (c == null ? "FAILED" : "ok"));
    }

    static void Stage(IModelDoc2 model, string label)
    {
        object bo = ((IPartDoc)model).GetBodies2(0, true);
        object[] b = bo as object[];
        double v = 0;
        int f = 0;
        int n = b == null ? 0 : b.Length;
        string detail = "";
        for (int i = 0; i < n; i++)
        {
            double[] mp = (double[])((IBody2)b[i]).GetMassProperties(1.0);
            v += mp[3];
            f += ((IBody2)b[i]).GetFaceCount();
            detail += String.Format(" | {0:F1}mm3 @({1:F2},{2:F2},{3:F2})",
                mp[3] * 1e9, mp[0] * 1e3, mp[1] * 1e3, mp[2] * 1e3);
        }
        Log(String.Format("  [stage] {0,-22} {1} body(ies) {2,10:F1} mm3 {3,4} faces{4}",
            label, n, v * 1e9, f, detail));
    }

    static void Report(IModelDoc2 model)
    {
        // GetBodies2 is on IPartDoc, not IModelDoc2.
        object bodiesObj = ((IPartDoc)model).GetBodies2(0, true);   // 0 = swSolidBody
        object[] bodies = bodiesObj as object[];
        int n = bodies == null ? 0 : bodies.Length;
        Log("solid bodies: " + n);
        double total = 0;
        for (int i = 0; i < n; i++)
        {
            IBody2 b = (IBody2)bodies[i];
            double[] p = (double[])b.GetMassProperties(1.0);
            total += p[3];
            Log(String.Format(
                "  body {0}: volume {1,10:F3} mm3   faces {2,3}   centroid ({3:F2},{4:F2},{5:F2}) mm",
                i, p[3] * 1e9, b.GetFaceCount(), p[0] * 1e3, p[1] * 1e3, p[2] * 1e3));
        }
        Log(String.Format("total volume: {0:F3} mm3", total * 1e9));
    }

    // A print-ready part should be one solid. Booleans on geometry this intricate
    // can shed a fragment far too small to manufacture -- Combine-Add will not
    // absorb it either, since Add needs the bodies to intersect -- so anything
    // under the threshold is deleted outright and reported.
    static void DropFragments(IModelDoc2 model, double minVolume)
    {
        if (minVolume <= 0) return;
        object bo = ((IPartDoc)model).GetBodies2(0, true);
        object[] bodies = bo as object[];
        if (bodies == null || bodies.Length < 2) return;
        model.ClearSelection2(true);
        int dropped = 0;
        double lost = 0;
        for (int i = 0; i < bodies.Length; i++)
        {
            double[] p = (double[])((IBody2)bodies[i]).GetMassProperties(1.0);
            if (p[3] < minVolume)
            {
                ((Body2)bodies[i]).Select2(true, null);
                dropped++;
                lost += p[3];
                Log(String.Format(
                    "  dropping fragment: {0:F4} mm3 at ({1:F2},{2:F2},{3:F2}) mm",
                    p[3] * 1e9, p[0] * 1e3, p[1] * 1e3, p[2] * 1e3));
            }
        }
        if (dropped == 0) { model.ClearSelection2(true); return; }
        IFeature f = model.FeatureManager.InsertDeleteBody2(false);
        Log("dropped " + dropped + " fragment(s) totalling "
            + (lost * 1e9).ToString("F4") + " mm3: " + (f == null ? "FAILED" : "ok"));
        model.ClearSelection2(true);
    }

    static void Save(IModelDoc2 model, string path)
    {
        if (String.IsNullOrEmpty(path)) return;
        int errs = 0, warns = 0;
        bool ok = model.Extension.SaveAs(path, 0, 1, null, ref errs, ref warns);
        Log(ok ? "saved: " + path
               : "WARNING: SaveAs failed, errs=" + errs + " warns=" + warns);
    }

    // profiles[i] is one sketch's worth of splines; profiles[i][j] is a flat
    // [x,y,z, x,y,z, ...] point list.
    public static string Build(double[][][] profiles, string[] tags, string[] names,
                               string plane, double xLo, double xHi, string savePath,
                               bool doOffset, double halfT, int capEnds, bool axisY,
                               bool mergeRevolves)
    {
        const double REV_ANGLE = 6.28318530717959;
        ISldWorks app = (ISldWorks)new SldWorks();
        app.Visible = true;
        Log("SOLIDWORKS " + app.RevisionNumber());

        IModelDoc2 model = (IModelDoc2)app.NewPart();
        if (model == null) return log + "ERROR: NewPart failed";
        ISketchManager sk = model.SketchManager;
        sk.DisplayWhenAdded = false;

        for (int i = 0; i < profiles.Length; i++)
        {
            Log("building " + tags[i] + " ...");
            if (!OpenSketch(model, plane, tags[i])) return log.ToString();

            ISketchSegment last = null;
            sk.AddToDB = true;   // exact coordinates, no snapping or auto-relations
            for (int j = 0; j < profiles[i].Length; j++)
            {
                last = sk.CreateSpline(profiles[i][j]);
                if (last == null)
                {
                    Log("ERROR: CreateSpline failed for " + tags[i] + " run " + (j + 1));
                    return log.ToString();
                }
            }
            sk.AddToDB = false;

            if (doOffset)
            {
                model.ClearSelection2(true);
                last.Select4(false, null);
                // ISketchManager.SketchOffset2, not IModelDoc2's 3-arg version:
                // only this one can cap the ends.
                if (!sk.SketchOffset2(halfT, true, false, capEnds, 0, false))
                {
                    Log("ERROR: SketchOffset2 failed for " + tags[i]);
                    return log.ToString();
                }
                last.ConstructionGeometry = true;
            }

            ISketchSegment ax = axisY ? sk.CreateCenterLine(0, xLo, 0, 0, xHi, 0)
                                      : sk.CreateCenterLine(xLo, 0, 0, xHi, 0, 0);
            if (ax == null)
            {
                Log("ERROR: CreateCenterLine failed for " + tags[i]);
                return log.ToString();
            }
            if (!CloseAndRevolve(model, tags[i], names[i], REV_ANGLE, mergeRevolves))
                return log.ToString();
        }

        model.ClearSelection2(true);
        sk.DisplayWhenAdded = true;
        model.EditRebuild3();

        // Safety net only: incremental merging normally leaves one body.
        if (((object[])((IPartDoc)model).GetBodies2(0, true)).Length > 1) CombineAll(model);

        model.ViewZoomtofit2();
        Report(model);
        Save(model, savePath);
        return log.ToString();
    }
    // ---------------- transducer interface merge ----------------

    static bool OpenSketchOn(IModelDoc2 model, string plane, string tag)
    {
        return OpenSketch(model, plane, tag);
    }

    // Trim the inserted collar. A revolved *cut* is rejected here, so the tool is
    // made as an ordinary boss revolve -- which is well proven -- and removed with
    // a body-level Combine-Subtract instead.
    //
    // Axial goes on sketch X: measured on this template, that revolves about
    // global +Y, which is the axis the interface part is built about. Sketch Y
    // would revolve about global Z and silently mis-assemble the part.
    static bool TrimAbove(IModelDoc2 model, string plane, double cutY,
                          double trimR, double trimH)
    {
        ISketchManager sk = model.SketchManager;
        if (!OpenSketch(model, plane, "collar trim")) return false;
        double r0 = 1.0e-4;
        sk.AddToDB = true;
        sk.CreateLine(cutY, r0, 0, cutY, trimR, 0);
        sk.CreateLine(cutY, trimR, 0, cutY + trimH, trimR, 0);
        sk.CreateLine(cutY + trimH, trimR, 0, cutY + trimH, r0, 0);
        sk.CreateLine(cutY + trimH, r0, 0, cutY, r0, 0);
        sk.AddToDB = false;
        sk.CreateCenterLine(cutY - 0.01, 0, 0, cutY + trimH + 0.01, 0, 0);
        model.ClearSelection2(true);
        sk.InsertSketch(true);

        IFeature f = (IFeature)model.FeatureByPositionReverse(0);
        if (f == null) { Log("ERROR: trim sketch not found"); return false; }
        f.Name = "MS_TrimProfile";
        Log("  trim sketch contours: " + ContourInfo(f));
        model.ClearSelection2(true);
        f.Select2(false, 0);
        IFeature tool = model.FeatureManager.FeatureRevolve2(
            true, true, false, false, false, false, 0, 0, 6.28318530717959, 0,
            false, false, 0, 0, 0, 0, 0, /*merge*/ false, true, true);
        if (tool == null) { Log("ERROR: trim tool revolve failed"); return false; }
        tool.Name = "MS_TrimTool";

        // Tell the two bodies apart by volume against the tool's analytic value.
        // GetBodyBox is no help: on these bodies it reports symmetric +/-extents
        // rather than absolute min/max, so it cannot say which side of the cut
        // plane a body sits on.
        object[] bodies = (object[])((IPartDoc)model).GetBodies2(0, true);
        if (bodies == null || bodies.Length != 2)
        {
            Log("ERROR: expected 2 bodies before the trim, found "
                + (bodies == null ? 0 : bodies.Length));
            return false;
        }
        double want = Math.PI * trimR * trimR * trimH;
        Body2 keep = null, remove = null;
        double bestErr = double.MaxValue;
        int removeIdx = -1;
        for (int i = 0; i < bodies.Length; i++)
        {
            double[] mp = (double[])((IBody2)bodies[i]).GetMassProperties(1.0);
            double err = Math.Abs(mp[3] - want) / want;
            if (err < bestErr) { bestErr = err; removeIdx = i; }
        }
        if (removeIdx < 0 || bestErr > 0.05)
        {
            Log("ERROR: could not identify the trim tool by volume (best mismatch "
                + (bestErr * 100).ToString("F1") + "%)");
            return false;
        }
        remove = (Body2)bodies[removeIdx];
        keep = (Body2)bodies[1 - removeIdx];
        model.ClearSelection2(true);
        object c = null;
        try { c = model.FeatureManager.InsertCombineFeature(15902, keep, new Body2[] { remove }); }
        catch (Exception e) { Log("trim combine threw: " + e.Message); }
        if (c == null) { Log("ERROR: collar trim (combine-subtract) failed"); return false; }
        ((IFeature)c).Name = "MS_TrimCollar";
        Log("  collar trimmed above y = " + (cutY * 1e3).ToString("F2") + " mm");
        return true;
    }

    // Which global axis does this body extend along? Taken as the largest
    // centroid component, with the others required to be much smaller.
    //
    // Deliberately loose, not exact: a real mounting collar carries features that
    // break axisymmetry -- JAXdomeV2's four small holes put its centroid ~1.9 mm
    // off axis -- so demanding a centroid exactly on the axis would reject valid
    // geometry. A genuinely mis-oriented body is off by tens of millimetres, so a
    // relative test separates the two cleanly.
    static int AxisOf(IBody2 b)
    {
        double[] mp = (double[])b.GetMassProperties(1.0);
        double[] c = new double[] { Math.Abs(mp[0]), Math.Abs(mp[1]), Math.Abs(mp[2]) };
        int big = 0;
        for (int i = 1; i < 3; i++) if (c[i] > c[big]) big = i;
        if (c[big] < 1.0e-4) return -2;          // sitting at the origin: no information
        double others = 0;
        for (int i = 0; i < 3; i++) if (i != big) others = Math.Max(others, c[i]);
        if (others > 0.35 * c[big]) return -1;   // not aligned with any axis
        return big;
    }

    static string AxisName(int a)
    {
        return a == 0 ? "X" : a == 1 ? "Y" : a == 2 ? "Z" : "none";
    }

    static string ContourInfo(IFeature skFeat)
    {
        try
        {
            ISketch s = (ISketch)skFeat.GetSpecificFeature2();
            int n = s.GetSketchContourCount();
            string outp = n.ToString();
            object co = s.GetSketchContours();
            if (co != null)
            {
                object[] arr = (object[])co;
                for (int i = 0; i < arr.Length; i++)
                    outp += " [" + ((ISketchContour)arr[i]).GetSketchSegmentsCount()
                          + " seg, closed=" + ((ISketchContour)arr[i]).IsClosed() + "]";
            }
            return outp;
        }
        catch (Exception e) { return "unavailable (" + e.Message + ")"; }
    }

    static bool BuildSkirt(IModelDoc2 model, string plane, double[] poly,
                           double axLo, double axHi)
    {
        ISketchManager sk = model.SketchManager;
        if (!OpenSketch(model, plane, "skirt")) return false;
        sk.AddToDB = true;
        int n = poly.Length / 3;
        for (int i = 0; i < n - 1; i++)
            sk.CreateLine(poly[i * 3], poly[i * 3 + 1], 0,
                          poly[(i + 1) * 3], poly[(i + 1) * 3 + 1], 0);
        sk.AddToDB = false;
        sk.CreateCenterLine(axLo, 0, 0, axHi, 0, 0);
        model.ClearSelection2(true);
        sk.InsertSketch(true);

        IFeature f = (IFeature)model.FeatureByPositionReverse(0);
        if (f == null) { Log("ERROR: skirt sketch not found"); return false; }
        f.Name = "MS_SkirtProfile";
        model.ClearSelection2(true);
        f.Select2(false, 0);
        IFeature rev = model.FeatureManager.FeatureRevolve2(
            true, true, false, false, false, false, 0, 0, 6.28318530717959, 0,
            false, false, 0, 0, 0, 0, 0, /*merge*/ true, true, true);
        if (rev == null) { Log("ERROR: skirt revolve failed"); return false; }
        rev.Name = "MS_Skirt";
        Log("  skirt revolved and merged");
        return true;
    }

    // All the axial holes -- the skirt vent ring and the rings that open the
    // enclosed cavities -- are cut by a single feature, since every one of them
    // is an axial through-hole. `rings` is flat: radius, diameter, count, phase.
    static bool Vents(IModelDoc2 model, string ventPlane, double[] rings,
                      double expectedRemoval)
    {
        if (rings == null || rings.Length < 4) return true;
        int total = VentSketch(model, ventPlane, rings);
        if (total < 0) return false;

        double before = TotalVolume(model);
        // The end condition is *verified*, not assumed. ThroughAllBoth (9)
        // reports success on this template but quietly honours the blind depths
        // instead, so the holes only reached a few millimetres either side of the
        // sketch plane and never touched the lens. A deep blind cut in both
        // directions is unambiguous, so try that first; the "through all" forms
        // are kept as fallbacks. Whichever is used has to actually remove the
        // material that lies along the holes' axes.
        int[] t1s = new int[] { 0, 0, 9, 1, 1 };
        bool[] sds = new bool[] { false, false, false, true, true };
        bool[] dirs = new bool[] { false, true, false, false, true };
        const double deep = 0.25;   // 250 mm, far beyond any part this builds

        for (int k = 0; k < t1s.Length; k++)
        {
            if (!SelectVentSketch(model))
            {
                Log("ERROR: the vent sketch is gone, so no further end condition "
                    + "can be tried");
                return false;
            }
            string how = "T1=" + t1s[k] + " Sd=" + sds[k] + " Dir=" + dirs[k];
            IFeature cut = null;
            try
            {
                cut = model.FeatureManager.FeatureCut4(
                    sds[k], false, dirs[k], t1s[k], 0, deep, deep, false, false,
                    false, false, 0, 0, false, false, false, false, false, false,
                    true, true, false, false, 0, 0, false, false);
            }
            catch (Exception e) { Log("    " + how + ": threw " + e.Message); }
            if (cut == null) { Log("    " + how + ": rejected"); continue; }

            double removed = before - TotalVolume(model);
            Log(String.Format("    {0}: removed {1:F1} mm3, expected {2:F1}",
                how, removed * 1e9, expectedRemoval * 1e9));

            if (expectedRemoval <= 0 || removed >= 0.5 * expectedRemoval)
            {
                cut.Name = "MS_Vents";
                Log(String.Format("  {0} vent holes cut via {1}: {2:F1} mm3 "
                                  + "({3:F0}% of expected)",
                    total, how, removed * 1e9,
                    expectedRemoval > 0 ? 100.0 * removed / expectedRemoval : 100.0));
                return true;
            }
            Log("    too little removed -- the holes are not reaching the shells; "
                + "discarding this cut");
            DeleteFeature(model, cut);
        }
        Log("ERROR: no end condition drove the vent holes through the material they "
            + "must pierce, so cavities would stay sealed");
        return false;
    }

    // Draws every ring into one sketch named MS_VentProfile. Returns the hole
    // count, or -1 on failure.
    static int VentSketch(IModelDoc2 model, string ventPlane, double[] rings)
    {
        ISketchManager sk = model.SketchManager;
        // The vent sketch needs a plane *perpendicular* to the revolve axis so the
        // holes come out axial. On this template that is the Right plane, not the
        // Top plane -- the default planes are cyclically permuted from the usual
        // convention.
        if (!OpenSketch(model, ventPlane, "vents")) return -1;
        sk.AddToDB = true;
        int total = 0;
        for (int k = 0; k + 3 < rings.Length; k += 4)
        {
            double radius = rings[k];
            double dia = rings[k + 1];
            int count = (int)Math.Round(rings[k + 2]);
            double phase = rings[k + 3];
            for (int i = 0; i < count; i++)
            {
                double a = phase + 2.0 * Math.PI * i / count;
                sk.CreateCircleByRadius(radius * Math.Cos(a), radius * Math.Sin(a), 0,
                                        dia / 2.0);
                total++;
            }
            Log(String.Format("    ring r={0,6:F2} mm  dia {1:F2} mm  x{2}",
                radius * 1e3, dia * 1e3, count));
        }
        sk.AddToDB = false;
        model.ClearSelection2(true);
        sk.InsertSketch(true);

        IFeature f = (IFeature)model.FeatureByPositionReverse(0);
        if (f == null) { Log("ERROR: vent sketch not found"); return -1; }
        f.Name = "MS_VentProfile";
        return total;
    }

    // Re-select by name rather than holding a reference: deleting a trial cut can
    // take its absorbed sketch with it, and a stale reference would not show that.
    static bool SelectVentSketch(IModelDoc2 model)
    {
        model.ClearSelection2(true);
        return model.Extension.SelectByID2("MS_VentProfile", "SKETCH", 0, 0, 0,
                                           false, 0, null, 0);
    }

    static double TotalVolume(IModelDoc2 model)
    {
        object bo = ((IPartDoc)model).GetBodies2(0, true);
        object[] b = bo as object[];
        double v = 0;
        for (int i = 0; b != null && i < b.Length; i++)
            v += ((double[])((IBody2)b[i]).GetMassProperties(1.0))[3];
        return v;
    }

    static void DeleteFeature(IModelDoc2 model, IFeature feat)
    {
        try
        {
            model.ClearSelection2(true);
            feat.Select2(false, 0);
            model.Extension.DeleteSelection2(0);
        }
        catch (Exception e) { Log("    could not discard the trial cut: " + e.Message); }
        model.ClearSelection2(true);
    }

    // The plane-to-global mapping is template-dependent, so verify rather than
    // assume: every body here must be a solid of revolution about the same global
    // axis. If the lens comes out about a different axis from the collar the part
    // is quietly mis-assembled, which is much worse than failing here.
    static bool CheckCoaxial(IModelDoc2 model)
    {
        object bo = ((IPartDoc)model).GetBodies2(0, true);
        object[] b = bo as object[];
        if (b == null || b.Length < 2) return true;
        int axis = -2;
        for (int i = 0; i < b.Length; i++)
        {
            double[] mp = (double[])((IBody2)b[i]).GetMassProperties(1.0);
            if (mp[3] < 1e-9) continue;          // ignore specks
            int a = AxisOf((IBody2)b[i]);
            if (a == -2) continue;               // no information from this body
            if (a < 0)
            {
                Log("ERROR: body " + i + " is not centred on any global axis "
                    + String.Format("(centroid {0:F2},{1:F2},{2:F2} mm)",
                        mp[0] * 1e3, mp[1] * 1e3, mp[2] * 1e3));
                return false;
            }
            if (axis == -2) axis = a;
            else if (a != axis)
            {
                Log("ERROR: bodies are not coaxial -- one is about global "
                    + AxisName(axis) + ", another about global " + AxisName(a)
                    + ". The sketch-plane mapping is wrong for this template.");
                return false;
            }
        }
        Log("  [check] bodies coaxial about global " + AxisName(axis));
        return true;
    }

    public static string BuildMerged(
        double[][][] profiles, string[] tags, string[] names, string plane,
        double axLo, double axHi, string savePath,
        string collarPath, double cutY, double trimR, double trimH,
        double[] skirtPoly, double[] ventRings, double expectedRemoval,
        double minFragment, string ventPlane)
    {
        const double REV_ANGLE = 6.28318530717959;
        ISldWorks app = (ISldWorks)new SldWorks();
        app.Visible = true;
        Log("SOLIDWORKS " + app.RevisionNumber());

        IModelDoc2 model = (IModelDoc2)app.NewPart();
        if (model == null) return log + "ERROR: NewPart failed";
        ISketchManager sk = model.SketchManager;
        sk.DisplayWhenAdded = false;

        // 1. bring in the collar by *copying its body*, not InsertPart3.
        //    InsertPart3 with swInsertPartBreakLink (512) imports different
        //    geometry -- 95173.8 mm3 / 47 faces instead of the part's actual
        //    81379.8 mm3 / 38 faces. Copying the body is exact, and leaves no
        //    external reference, so the result is a standalone print-ready part.
        Log("copying interface body from " + collarPath + " ...");
        string target = model.GetTitle();
        int oe = 0, ow = 0;
        IModelDoc2 src = (IModelDoc2)app.OpenDoc6(collarPath, 1, 0, "", ref oe, ref ow);
        if (src == null) { Log("ERROR: could not open " + collarPath); return log.ToString(); }
        object srcBodies = ((IPartDoc)src).GetBodies2(0, true);
        object[] sba = srcBodies as object[];
        if (sba == null || sba.Length == 0)
        {
            Log("ERROR: interface part has no solid body");
            return log.ToString();
        }
        if (sba.Length > 1) Log("  note: interface part has " + sba.Length
                                + " bodies; copying all of them");
        object[] copies = new object[sba.Length];
        for (int i = 0; i < sba.Length; i++) copies[i] = ((IBody2)sba[i]).Copy();
        double srcVol = 0;
        for (int i = 0; i < sba.Length; i++)
            srcVol += ((double[])((IBody2)sba[i]).GetMassProperties(1.0))[3];
        Log(String.Format("  source volume {0:F1} mm3", srcVol * 1e9));

        int ae = 0;
        app.ActivateDoc3(target, true, 0, ref ae);
        for (int i = 0; i < copies.Length; i++)
        {
            object bf = ((IPartDoc)model).CreateFeatureFromBody3(copies[i], false, 0);
            if (bf == null)
            {
                Log("ERROR: CreateFeatureFromBody3 failed for body " + i);
                return log.ToString();
            }
        }
        app.CloseDoc(src.GetTitle());
        app.ActivateDoc3(target, true, 0, ref ae);
        object[] after = (object[])((IPartDoc)model).GetBodies2(0, true);
        double gotVol = 0;
        for (int i = 0; i < after.Length; i++)
            gotVol += ((double[])((IBody2)after[i]).GetMassProperties(1.0))[3];
        Log(String.Format("  copied, bodies now: {0}, volume {1:F1} mm3", after.Length,
            gotVol * 1e9));
        if (Math.Abs(gotVol - srcVol) / srcVol > 1e-6)
            Log("WARNING: copied volume differs from the source part");

        // 2. keep only the mount
        Stage(model, "after copy");
        if (!TrimAbove(model, plane, cutY, trimR, trimH)) return log.ToString();
        Stage(model, "after trim");

        // 3. the lens itself
        for (int i = 0; i < profiles.Length; i++)
        {
            Log("building " + tags[i] + " ...");
            if (!OpenSketch(model, plane, tags[i])) return log.ToString();
            sk.AddToDB = true;
            for (int j = 0; j < profiles[i].Length; j++)
            {
                if (sk.CreateSpline(profiles[i][j]) == null)
                {
                    Log("ERROR: CreateSpline failed for " + tags[i] + " run " + (j + 1));
                    return log.ToString();
                }
            }
            sk.AddToDB = false;
            // axial on sketch X => revolve about global Y (see TrimAbove)
            if (sk.CreateCenterLine(axLo, 0, 0, axHi, 0, 0) == null)
            {
                Log("ERROR: CreateCenterLine failed for " + tags[i]);
                return log.ToString();
            }
            if (!CloseAndRevolve(model, tags[i], names[i], REV_ANGLE, true))
                return log.ToString();
            Stage(model, "after " + tags[i]);
            if (i == 0 && !CheckCoaxial(model)) return log.ToString();
        }

        // 4. bridge lens to mount, then vent it
        if (!BuildSkirt(model, plane, skirtPoly, axLo, axHi)) return log.ToString();
        Stage(model, "after skirt");
        if (!Vents(model, ventPlane, ventRings, expectedRemoval)) return log.ToString();
        Stage(model, "after vents");

        model.ClearSelection2(true);
        sk.DisplayWhenAdded = true;
        model.EditRebuild3();
        DropFragments(model, minFragment);
        if (((object[])((IPartDoc)model).GetBodies2(0, true)).Length > 1) CombineAll(model);
        model.ViewZoomtofit2();
        Report(model);
        Save(model, savePath);
        return log.ToString();
    }
}
'@
Add-Type -TypeDefinition $cs -ReferencedAssemblies $dlls

$p0_0 = [double[]]@(
        0.0487793464, 0.0039201495, 0.0000000000,
        0.0487761757, 0.0039354736, 0.0000000000,
        0.0487887740, 0.0039838319, 0.0000000000,
        0.0488164869, 0.0040902202, 0.0000000000,
        0.0488850665, 0.0043720027, 0.0000000000,
        0.0490010630, 0.0048994350, 0.0000000000,
        0.0492224908, 0.0063117752, 0.0000000000,
        0.0491970058, 0.0075175952, 0.0000000000,
        0.0491658511, 0.0076333619, 0.0000000000,
        0.0490286820, 0.0078988119, 0.0000000000,
        0.0488995701, 0.0080373583, 0.0000000000,
        0.0484635620, 0.0081945321, 0.0000000000,
        0.0480495125, 0.0080917003, 0.0000000000,
        0.0476803175, 0.0078526406, 0.0000000000,
        0.0471997712, 0.0074299070, 0.0000000000,
        0.0460761381, 0.0063263302, 0.0000000000,
        0.0453444696, 0.0056821173, 0.0000000000,
        0.0445576289, 0.0051712090, 0.0000000000,
        0.0441300825, 0.0050345273, 0.0000000000,
        0.0436714032, 0.0050466829, 0.0000000000,
        0.0427913564, 0.0053401596, 0.0000000000,
        0.0417121779, 0.0058867038, 0.0000000000,
        0.0403698395, 0.0065076780, 0.0000000000,
        0.0390456075, 0.0067923991, 0.0000000000,
        0.0381425035, 0.0067041111, 0.0000000000,
        0.0377130645, 0.0065692331, 0.0000000000,
        0.0368019039, 0.0061592375, 0.0000000000,
        0.0355684432, 0.0054363231, 0.0000000000,
        0.0338384573, 0.0042818790, 0.0000000000,
        0.0330134341, 0.0037345274, 0.0000000000,
        0.0322010524, 0.0032617886, 0.0000000000
    )
$p0_1 = [double[]]@(
        0.0322010524, 0.0032617886, 0.0000000000,
        0.0321920204, 0.0032575674, 0.0000000000,
        0.0321784726, 0.0032512356, 0.0000000000,
        0.0321747877, 0.0032495127, 0.0000000000
    )
$p0_2 = [double[]]@(
        0.0321747877, 0.0032495127, 0.0000000000,
        0.0321639283, 0.0032618062, 0.0000000000,
        0.0321850575, 0.0033203183, 0.0000000000,
        0.0322088894, 0.0033861333, 0.0000000000,
        0.0322921728, 0.0035898265, 0.0000000000,
        0.0324233543, 0.0038817870, 0.0000000000,
        0.0325564879, 0.0041616901, 0.0000000000,
        0.0327648648, 0.0045829593, 0.0000000000,
        0.0331144883, 0.0052745804, 0.0000000000,
        0.0336762824, 0.0064523213, 0.0000000000,
        0.0338448385, 0.0068748837, 0.0000000000,
        0.0340485776, 0.0077681329, 0.0000000000,
        0.0340080248, 0.0081149723, 0.0000000000,
        0.0337101050, 0.0085437916, 0.0000000000,
        0.0334104424, 0.0087029560, 0.0000000000,
        0.0324961697, 0.0087967555, 0.0000000000,
        0.0315300633, 0.0086677232, 0.0000000000,
        0.0309530731, 0.0085450774, 0.0000000000,
        0.0295935589, 0.0081906379, 0.0000000000,
        0.0287951603, 0.0079639178, 0.0000000000,
        0.0284000650, 0.0078545360, 0.0000000000,
        0.0281821859, 0.0077983170, 0.0000000000,
        0.0280114160, 0.0077589955, 0.0000000000,
        0.0277711733, 0.0076932096, 0.0000000000,
        0.0276568953, 0.0076123460, 0.0000000000,
        0.0275381561, 0.0074402156, 0.0000000000,
        0.0275009877, 0.0072800431, 0.0000000000,
        0.0275064391, 0.0071686651, 0.0000000000,
        0.0277031961, 0.0068462681, 0.0000000000,
        0.0279552780, 0.0067506489, 0.0000000000,
        0.0283109005, 0.0068011823, 0.0000000000,
        0.0288770751, 0.0069482364, 0.0000000000,
        0.0292571943, 0.0070555970, 0.0000000000,
        0.0298295044, 0.0072182650, 0.0000000000,
        0.0303210548, 0.0073541235, 0.0000000000,
        0.0311840039, 0.0075720834, 0.0000000000,
        0.0317464801, 0.0076910057, 0.0000000000,
        0.0324092660, 0.0077878173, 0.0000000000,
        0.0328088062, 0.0078027806, 0.0000000000,
        0.0330272799, 0.0077759267, 0.0000000000
    )
$p0_3 = [double[]]@(
        0.0330272799, 0.0077759267, 0.0000000000,
        0.0330323113, 0.0077744957, 0.0000000000,
        0.0330404210, 0.0077718460, 0.0000000000,
        0.0330415757, 0.0077714667, 0.0000000000
    )
$p0_4 = [double[]]@(
        0.0330415757, 0.0077714667, 0.0000000000,
        0.0330482346, 0.0077551451, 0.0000000000,
        0.0330415688, 0.0077044472, 0.0000000000,
        0.0330291545, 0.0076256749, 0.0000000000,
        0.0329688095, 0.0074039233, 0.0000000000,
        0.0328621359, 0.0071020065, 0.0000000000,
        0.0323375779, 0.0059566646, 0.0000000000,
        0.0313336161, 0.0038878446, 0.0000000000,
        0.0310975920, 0.0031458591, 0.0000000000,
        0.0310735911, 0.0028672355, 0.0000000000,
        0.0311544667, 0.0025289137, 0.0000000000,
        0.0312689520, 0.0023534063, 0.0000000000,
        0.0314883191, 0.0021958142, 0.0000000000,
        0.0318492569, 0.0021253002, 0.0000000000,
        0.0325478780, 0.0023200575, 0.0000000000,
        0.0335888993, 0.0029154776, 0.0000000000,
        0.0339237987, 0.0031341479, 0.0000000000,
        0.0344795743, 0.0035083075, 0.0000000000,
        0.0366723462, 0.0049415204, 0.0000000000,
        0.0376781939, 0.0054766588, 0.0000000000,
        0.0385787157, 0.0057725252, 0.0000000000,
        0.0391475324, 0.0057842302, 0.0000000000,
        0.0400103458, 0.0055743996, 0.0000000000,
        0.0411015893, 0.0050771734, 0.0000000000,
        0.0423133109, 0.0044593268, 0.0000000000,
        0.0433182804, 0.0040965188, 0.0000000000,
        0.0440332054, 0.0040224662, 0.0000000000,
        0.0447740842, 0.0041775237, 0.0000000000,
        0.0455650218, 0.0046032213, 0.0000000000,
        0.0465439561, 0.0053949394, 0.0000000000,
        0.0474976604, 0.0063217855, 0.0000000000,
        0.0482489599, 0.0070282807, 0.0000000000
    )
$p0_5 = [double[]]@(
        0.0482489599, 0.0070282807, 0.0000000000,
        0.0482507395, 0.0067165495, 0.0000000000,
        0.0481803999, 0.0060153022, 0.0000000000,
        0.0480032034, 0.0050109684, 0.0000000000,
        0.0477653913, 0.0040286135, 0.0000000000
    )
$p0_6 = [double[]]@(
        0.0477653913, 0.0040286135, 0.0000000000,
        0.0477547320, 0.0040218951, 0.0000000000,
        0.0477049737, 0.0040266752, 0.0000000000,
        0.0476303129, 0.0040335983, 0.0000000000,
        0.0475357312, 0.0040422454, 0.0000000000,
        0.0474112816, 0.0040536231, 0.0000000000,
        0.0471373508, 0.0040772873, 0.0000000000,
        0.0466686404, 0.0041121875, 0.0000000000,
        0.0462039768, 0.0041279611, 0.0000000000,
        0.0458773758, 0.0040865206, 0.0000000000,
        0.0455996076, 0.0039533211, 0.0000000000,
        0.0453927131, 0.0036235895, 0.0000000000,
        0.0454479828, 0.0032101270, 0.0000000000,
        0.0458058740, 0.0028378143, 0.0000000000,
        0.0465765412, 0.0024606027, 0.0000000000,
        0.0472664130, 0.0022977762, 0.0000000000,
        0.0478712039, 0.0023395699, 0.0000000000,
        0.0482081552, 0.0025312704, 0.0000000000,
        0.0483940391, 0.0027904995, 0.0000000000,
        0.0484691285, 0.0029465611, 0.0000000000
    )
$p0_7 = [double[]]@(
        0.0484691285, 0.0029465611, 0.0000000000,
        0.0509532979, 0.0026883031, 0.0000000000,
        0.0538792779, 0.0024025448, 0.0000000000,
        0.0549955270, 0.0023112564, 0.0000000000,
        0.0557437928, 0.0022605812, 0.0000000000,
        0.0570327000, 0.0022121185, 0.0000000000,
        0.0579575490, 0.0022389938, 0.0000000000,
        0.0596872318, 0.0024611913, 0.0000000000,
        0.0607091171, 0.0027013979, 0.0000000000,
        0.0612479966, 0.0028538874, 0.0000000000,
        0.0615936645, 0.0029543041, 0.0000000000,
        0.0619320469, 0.0030439823, 0.0000000000,
        0.0621937913, 0.0031076973, 0.0000000000,
        0.0623588592, 0.0032204486, 0.0000000000,
        0.0624989409, 0.0035361036, 0.0000000000,
        0.0624570652, 0.0037713223, 0.0000000000,
        0.0622945151, 0.0039726691, 0.0000000000,
        0.0621325395, 0.0040507274, 0.0000000000,
        0.0619833067, 0.0040683357, 0.0000000000,
        0.0617470926, 0.0040273882, 0.0000000000,
        0.0614079808, 0.0039409017, 0.0000000000,
        0.0611292407, 0.0038609720, 0.0000000000,
        0.0606200049, 0.0037140498, 0.0000000000,
        0.0598056818, 0.0035080286, 0.0000000000,
        0.0582655431, 0.0032660229, 0.0000000000,
        0.0574468926, 0.0032175735, 0.0000000000,
        0.0557680461, 0.0032608540, 0.0000000000,
        0.0548003626, 0.0033289185, 0.0000000000,
        0.0533160707, 0.0034581302, 0.0000000000,
        0.0514651448, 0.0036408481, 0.0000000000,
        0.0499832023, 0.0037949812, 0.0000000000,
        0.0487793464, 0.0039201495, 0.0000000000
    )
$profile0 = New-Object 'double[][]' 8
$profile0[0] = $p0_0
$profile0[1] = $p0_1
$profile0[2] = $p0_2
$profile0[3] = $p0_3
$profile0[4] = $p0_4
$profile0[5] = $p0_5
$profile0[6] = $p0_6
$profile0[7] = $p0_7

$p1_0 = [double[]]@(
        0.0496855168, 0.0038158671, 0.0000000000,
        0.0497038940, 0.0039546454, 0.0000000000,
        0.0497498060, 0.0040869235, 0.0000000000,
        0.0499673164, 0.0044918819, 0.0000000000,
        0.0502834019, 0.0049424101, 0.0000000000,
        0.0510087263, 0.0058087318, 0.0000000000,
        0.0522772837, 0.0071549813, 0.0000000000,
        0.0530456819, 0.0079699991, 0.0000000000,
        0.0533797968, 0.0083553191, 0.0000000000,
        0.0535682768, 0.0086017134, 0.0000000000,
        0.0537079486, 0.0088207014, 0.0000000000,
        0.0538589700, 0.0090689680, 0.0000000000,
        0.0539895273, 0.0092206045, 0.0000000000,
        0.0541744136, 0.0093894070, 0.0000000000,
        0.0542736280, 0.0097044828, 0.0000000000,
        0.0541866126, 0.0099730720, 0.0000000000,
        0.0540763505, 0.0100890290, 0.0000000000,
        0.0539820428, 0.0101455224, 0.0000000000,
        0.0537774164, 0.0101916503, 0.0000000000,
        0.0535674350, 0.0101768528, 0.0000000000,
        0.0531585296, 0.0102028176, 0.0000000000,
        0.0525583758, 0.0103118177, 0.0000000000,
        0.0518576543, 0.0104258800, 0.0000000000,
        0.0512234253, 0.0105115299, 0.0000000000,
        0.0502903772, 0.0106256348, 0.0000000000,
        0.0491283391, 0.0107614956, 0.0000000000,
        0.0470490149, 0.0110167171, 0.0000000000,
        0.0444871408, 0.0114278830, 0.0000000000,
        0.0432994036, 0.0117447566, 0.0000000000,
        0.0427483749, 0.0120051056, 0.0000000000,
        0.0419990097, 0.0125530220, 0.0000000000,
        0.0412159002, 0.0133674801, 0.0000000000,
        0.0408426128, 0.0137714011, 0.0000000000,
        0.0404646960, 0.0140977357, 0.0000000000
    )
$p1_1 = [double[]]@(
        0.0404646960, 0.0140977357, 0.0000000000,
        0.0404396855, 0.0142369579, 0.0000000000,
        0.0404033962, 0.0143622450, 0.0000000000,
        0.0402635397, 0.0145817928, 0.0000000000,
        0.0400435727, 0.0147540468, 0.0000000000,
        0.0397913600, 0.0148501160, 0.0000000000,
        0.0393944086, 0.0148927924, 0.0000000000,
        0.0387553748, 0.0148615635, 0.0000000000,
        0.0379612792, 0.0147622961, 0.0000000000,
        0.0367680453, 0.0145615964, 0.0000000000,
        0.0363552524, 0.0144844359, 0.0000000000,
        0.0355113169, 0.0143187073, 0.0000000000,
        0.0334958896, 0.0138930121, 0.0000000000,
        0.0324609594, 0.0136639980, 0.0000000000,
        0.0304127616, 0.0132005435, 0.0000000000,
        0.0292230367, 0.0129307028, 0.0000000000,
        0.0286372973, 0.0128004068, 0.0000000000,
        0.0282658075, 0.0127202364, 0.0000000000,
        0.0280210085, 0.0126695570, 0.0000000000,
        0.0277983838, 0.0126128242, 0.0000000000,
        0.0275695859, 0.0124097222, 0.0000000000,
        0.0275344835, 0.0123377412, 0.0000000000,
        0.0275070400, 0.0120716719, 0.0000000000,
        0.0276205994, 0.0118296157, 0.0000000000,
        0.0279303854, 0.0116601458, 0.0000000000,
        0.0282957829, 0.0117048332, 0.0000000000,
        0.0287750556, 0.0118069246, 0.0000000000,
        0.0293218991, 0.0119279141, 0.0000000000,
        0.0303361934, 0.0121575379, 0.0000000000,
        0.0308627036, 0.0122773999, 0.0000000000,
        0.0317500703, 0.0124789469, 0.0000000000,
        0.0323353428, 0.0126109650, 0.0000000000,
        0.0332527653, 0.0128155881, 0.0000000000,
        0.0345133954, 0.0130895714, 0.0000000000,
        0.0353941927, 0.0132742936, 0.0000000000,
        0.0360313700, 0.0134028070, 0.0000000000,
        0.0369153387, 0.0135720116, 0.0000000000,
        0.0374272463, 0.0136629488, 0.0000000000,
        0.0377824163, 0.0137222397, 0.0000000000,
        0.0380985633, 0.0137716904, 0.0000000000,
        0.0383363619, 0.0138048284, 0.0000000000,
        0.0385050166, 0.0138275044, 0.0000000000,
        0.0386142056, 0.0138401900, 0.0000000000,
        0.0386827415, 0.0138481542, 0.0000000000,
        0.0386949200, 0.0138322364, 0.0000000000
    )
$p1_2 = [double[]]@(
        0.0386949200, 0.0138322364, 0.0000000000,
        0.0383954835, 0.0134590961, 0.0000000000,
        0.0381030875, 0.0129994461, 0.0000000000,
        0.0379315708, 0.0126887069, 0.0000000000,
        0.0376863457, 0.0121964199, 0.0000000000,
        0.0375311962, 0.0118605917, 0.0000000000,
        0.0374580835, 0.0117014631, 0.0000000000,
        0.0374043247, 0.0116164447, 0.0000000000,
        0.0373461499, 0.0114356711, 0.0000000000,
        0.0374664574, 0.0110431664, 0.0000000000,
        0.0377788781, 0.0108768922, 0.0000000000,
        0.0380439411, 0.0109132332, 0.0000000000,
        0.0382872082, 0.0111289827, 0.0000000000
    )
$p1_3 = [double[]]@(
        0.0382872082, 0.0111289827, 0.0000000000,
        0.0385681987, 0.0114067147, 0.0000000000,
        0.0389245059, 0.0117575350, 0.0000000000,
        0.0392705576, 0.0121117064, 0.0000000000,
        0.0395415170, 0.0124058976, 0.0000000000,
        0.0397762002, 0.0126788588, 0.0000000000,
        0.0399106261, 0.0128468022, 0.0000000000,
        0.0399803573, 0.0129382322, 0.0000000000,
        0.0400303946, 0.0130069821, 0.0000000000,
        0.0400704032, 0.0130642956, 0.0000000000,
        0.0400932657, 0.0130970468, 0.0000000000,
        0.0401005774, 0.0130983125, 0.0000000000
    )
$p1_4 = [double[]]@(
        0.0401005774, 0.0130983125, 0.0000000000,
        0.0403348737, 0.0128521633, 0.0000000000,
        0.0408240495, 0.0123102872, 0.0000000000,
        0.0414910055, 0.0116701046, 0.0000000000,
        0.0424674462, 0.0110204539, 0.0000000000,
        0.0429523733, 0.0108066103, 0.0000000000,
        0.0437763295, 0.0105616436, 0.0000000000,
        0.0445633808, 0.0103930121, 0.0000000000,
        0.0457117689, 0.0101966527, 0.0000000000,
        0.0473212296, 0.0099729815, 0.0000000000,
        0.0482789215, 0.0098548345, 0.0000000000,
        0.0497686598, 0.0096800502, 0.0000000000,
        0.0506723039, 0.0095726568, 0.0000000000,
        0.0515153171, 0.0094642848, 0.0000000000,
        0.0518914922, 0.0094102497, 0.0000000000,
        0.0521088177, 0.0093761731, 0.0000000000,
        0.0523844608, 0.0093268349, 0.0000000000,
        0.0525707950, 0.0092897530, 0.0000000000,
        0.0527080987, 0.0092623477, 0.0000000000,
        0.0527845269, 0.0092490818, 0.0000000000,
        0.0527910861, 0.0092365776, 0.0000000000
    )
$p1_5 = [double[]]@(
        0.0527910861, 0.0092365776, 0.0000000000,
        0.0527877283, 0.0092310186, 0.0000000000,
        0.0527825749, 0.0092224789, 0.0000000000,
        0.0527798681, 0.0092181705, 0.0000000000
    )
$p1_6 = [double[]]@(
        0.0527798681, 0.0092181705, 0.0000000000,
        0.0524332169, 0.0087848569, 0.0000000000,
        0.0518008956, 0.0081030776, 0.0000000000,
        0.0508878938, 0.0071497733, 0.0000000000,
        0.0498137930, 0.0059574686, 0.0000000000,
        0.0494957737, 0.0055586202, 0.0000000000,
        0.0489872743, 0.0047984568, 0.0000000000,
        0.0488722098, 0.0045713333, 0.0000000000,
        0.0487769386, 0.0043341522, 0.0000000000,
        0.0486892968, 0.0039703888, 0.0000000000,
        0.0486855281, 0.0038201489, 0.0000000000,
        0.0486897800, 0.0036853151, 0.0000000000,
        0.0487162203, 0.0035680565, 0.0000000000,
        0.0487522081, 0.0034382317, 0.0000000000,
        0.0488378878, 0.0032790251, 0.0000000000,
        0.0489223943, 0.0031555069, 0.0000000000,
        0.0490314028, 0.0030517421, 0.0000000000,
        0.0491468683, 0.0029559994, 0.0000000000,
        0.0492368108, 0.0029015246, 0.0000000000,
        0.0493531620, 0.0028331916, 0.0000000000,
        0.0497292257, 0.0026839310, 0.0000000000,
        0.0503847285, 0.0025235214, 0.0000000000,
        0.0514260667, 0.0023908314, 0.0000000000,
        0.0528139798, 0.0023179294, 0.0000000000,
        0.0545439813, 0.0023096155, 0.0000000000,
        0.0564783991, 0.0023537704, 0.0000000000,
        0.0575578556, 0.0023871429, 0.0000000000,
        0.0583077200, 0.0024057450, 0.0000000000,
        0.0595811023, 0.0024584982, 0.0000000000,
        0.0606328276, 0.0026232276, 0.0000000000,
        0.0610542759, 0.0027307282, 0.0000000000,
        0.0615403050, 0.0028848828, 0.0000000000,
        0.0618383616, 0.0029868307, 0.0000000000,
        0.0620403904, 0.0030460352, 0.0000000000,
        0.0621427038, 0.0030694191, 0.0000000000,
        0.0622785167, 0.0031333776, 0.0000000000,
        0.0624322299, 0.0032972727, 0.0000000000,
        0.0624994897, 0.0035260602, 0.0000000000,
        0.0624591037, 0.0037466695, 0.0000000000,
        0.0622906726, 0.0039554497, 0.0000000000,
        0.0621567760, 0.0040234071, 0.0000000000,
        0.0619788356, 0.0040481738, 0.0000000000,
        0.0616852441, 0.0039861634, 0.0000000000,
        0.0612106901, 0.0038290322, 0.0000000000,
        0.0605547139, 0.0036322218, 0.0000000000,
        0.0589814994, 0.0034189380, 0.0000000000,
        0.0582917475, 0.0034056218, 0.0000000000,
        0.0576767986, 0.0033911164, 0.0000000000,
        0.0565074263, 0.0033550981, 0.0000000000,
        0.0547830142, 0.0033132528, 0.0000000000,
        0.0530431180, 0.0033136078, 0.0000000000,
        0.0522186232, 0.0033408536, 0.0000000000,
        0.0508442039, 0.0034618895, 0.0000000000,
        0.0501527990, 0.0035984754, 0.0000000000,
        0.0498834850, 0.0036924087, 0.0000000000,
        0.0498013964, 0.0037288586, 0.0000000000,
        0.0497111919, 0.0037852252, 0.0000000000,
        0.0496855168, 0.0038158671, 0.0000000000
    )
$profile1 = New-Object 'double[][]' 7
$profile1[0] = $p1_0
$profile1[1] = $p1_1
$profile1[2] = $p1_2
$profile1[3] = $p1_3
$profile1[4] = $p1_4
$profile1[5] = $p1_5
$profile1[6] = $p1_6

$p2_0 = [double[]]@(
        0.0622202317, 0.0087225901, 0.0000000000,
        0.0621209953, 0.0088211122, 0.0000000000,
        0.0619011684, 0.0090254568, 0.0000000000,
        0.0615031520, 0.0092930785, 0.0000000000,
        0.0608285808, 0.0095972798, 0.0000000000,
        0.0598752250, 0.0098985830, 0.0000000000,
        0.0587521278, 0.0101887314, 0.0000000000,
        0.0572888145, 0.0105405386, 0.0000000000,
        0.0557983661, 0.0108861677, 0.0000000000,
        0.0546966038, 0.0111395606, 0.0000000000
    )
$p2_1 = [double[]]@(
        0.0546966038, 0.0111395606, 0.0000000000,
        0.0545812409, 0.0112565083, 0.0000000000,
        0.0543460682, 0.0113774668, 0.0000000000,
        0.0539989944, 0.0114742029, 0.0000000000,
        0.0534554083, 0.0115862024, 0.0000000000,
        0.0530613408, 0.0116551013, 0.0000000000,
        0.0526760907, 0.0117156824, 0.0000000000,
        0.0521209592, 0.0117903692, 0.0000000000,
        0.0519020861, 0.0118118558, 0.0000000000,
        0.0516973103, 0.0118112642, 0.0000000000,
        0.0514099359, 0.0116787419, 0.0000000000,
        0.0513000980, 0.0115292723, 0.0000000000,
        0.0512542203, 0.0113702815, 0.0000000000,
        0.0512519908, 0.0112806038, 0.0000000000,
        0.0512669758, 0.0111860899, 0.0000000000,
        0.0512831068, 0.0111348988, 0.0000000000,
        0.0512765990, 0.0111195697, 0.0000000000
    )
$p2_2 = [double[]]@(
        0.0512765990, 0.0111195697, 0.0000000000,
        0.0505998347, 0.0110919666, 0.0000000000,
        0.0496503083, 0.0110605030, 0.0000000000,
        0.0486406113, 0.0110377422, 0.0000000000,
        0.0479605910, 0.0110307165, 0.0000000000,
        0.0462206370, 0.0110554300, 0.0000000000,
        0.0456216083, 0.0110891708, 0.0000000000,
        0.0447287231, 0.0111985709, 0.0000000000,
        0.0441661200, 0.0113738629, 0.0000000000,
        0.0437880733, 0.0116157700, 0.0000000000,
        0.0435827902, 0.0118349916, 0.0000000000,
        0.0430293775, 0.0127149454, 0.0000000000,
        0.0423132693, 0.0133724640, 0.0000000000,
        0.0419059911, 0.0135371420, 0.0000000000,
        0.0413151267, 0.0136351994, 0.0000000000,
        0.0400460514, 0.0136004943, 0.0000000000,
        0.0392467356, 0.0136118495, 0.0000000000,
        0.0387709923, 0.0137286860, 0.0000000000,
        0.0382963032, 0.0140719877, 0.0000000000,
        0.0380798045, 0.0144306386, 0.0000000000,
        0.0378313305, 0.0150844646, 0.0000000000,
        0.0375075082, 0.0163018594, 0.0000000000,
        0.0368826440, 0.0190310912, 0.0000000000,
        0.0367220356, 0.0195622726, 0.0000000000,
        0.0364709067, 0.0201561543, 0.0000000000,
        0.0361247799, 0.0206049867, 0.0000000000,
        0.0358274561, 0.0207678366, 0.0000000000,
        0.0355003195, 0.0207957564, 0.0000000000,
        0.0350199316, 0.0205635434, 0.0000000000,
        0.0346087164, 0.0200367689, 0.0000000000,
        0.0342029252, 0.0192453408, 0.0000000000,
        0.0338971353, 0.0185278391, 0.0000000000,
        0.0329686423, 0.0161528468, 0.0000000000,
        0.0322602261, 0.0145857699, 0.0000000000,
        0.0320873625, 0.0142934266, 0.0000000000,
        0.0319072153, 0.0140409444, 0.0000000000,
        0.0318111724, 0.0139397251, 0.0000000000,
        0.0317317915, 0.0138856016, 0.0000000000
    )
$p2_3 = [double[]]@(
        0.0317317915, 0.0138856016, 0.0000000000,
        0.0316259519, 0.0139172108, 0.0000000000,
        0.0314151138, 0.0140595193, 0.0000000000,
        0.0309033102, 0.0146135730, 0.0000000000,
        0.0302569162, 0.0155584099, 0.0000000000,
        0.0298908266, 0.0161727407, 0.0000000000,
        0.0295628734, 0.0167570358, 0.0000000000,
        0.0293186678, 0.0172047617, 0.0000000000,
        0.0291404021, 0.0175346799, 0.0000000000,
        0.0288024362, 0.0181534154, 0.0000000000,
        0.0286352344, 0.0184436117, 0.0000000000,
        0.0284641413, 0.0187146208, 0.0000000000,
        0.0282942611, 0.0189099672, 0.0000000000,
        0.0279486780, 0.0190030850, 0.0000000000,
        0.0276916110, 0.0188992939, 0.0000000000
    )
$p2_4 = [double[]]@(
        0.0276916110, 0.0188992939, 0.0000000000,
        0.0275804625, 0.0187777326, 0.0000000000,
        0.0275174261, 0.0186365757, 0.0000000000,
        0.0275019472, 0.0184616516, 0.0000000000,
        0.0275320692, 0.0183295444, 0.0000000000,
        0.0276532580, 0.0181292410, 0.0000000000,
        0.0277180482, 0.0180278439, 0.0000000000,
        0.0279322756, 0.0176605640, 0.0000000000,
        0.0282201724, 0.0171341622, 0.0000000000,
        0.0287313674, 0.0161940864, 0.0000000000,
        0.0289268601, 0.0158450980, 0.0000000000,
        0.0292485557, 0.0152918771, 0.0000000000,
        0.0298511299, 0.0143539200, 0.0000000000,
        0.0304876269, 0.0135637030, 0.0000000000,
        0.0309697149, 0.0131436598, 0.0000000000,
        0.0311945438, 0.0130132348, 0.0000000000,
        0.0313152738, 0.0129650370, 0.0000000000,
        0.0314232720, 0.0129254348, 0.0000000000,
        0.0315460405, 0.0129016868, 0.0000000000,
        0.0316946630, 0.0128818051, 0.0000000000,
        0.0318195829, 0.0128894380, 0.0000000000,
        0.0319239685, 0.0129000433, 0.0000000000,
        0.0321094102, 0.0129590874, 0.0000000000,
        0.0322463951, 0.0130205384, 0.0000000000,
        0.0323607896, 0.0131011664, 0.0000000000,
        0.0324681617, 0.0131830423, 0.0000000000,
        0.0325631130, 0.0132790085, 0.0000000000,
        0.0326660667, 0.0133879917, 0.0000000000,
        0.0329209948, 0.0137409817, 0.0000000000,
        0.0334954653, 0.0148330068, 0.0000000000,
        0.0337670900, 0.0154617505, 0.0000000000,
        0.0339876924, 0.0160091365, 0.0000000000,
        0.0345260603, 0.0173984399, 0.0000000000,
        0.0349655573, 0.0184936923, 0.0000000000,
        0.0352936886, 0.0192122496, 0.0000000000,
        0.0355444958, 0.0196441919, 0.0000000000
    )
$p2_5 = [double[]]@(
        0.0355444958, 0.0196441919, 0.0000000000,
        0.0355562075, 0.0196602197, 0.0000000000,
        0.0355679200, 0.0196762487, 0.0000000000,
        0.0355895235, 0.0196837550, 0.0000000000
    )
$p2_6 = [double[]]@(
        0.0355895235, 0.0196837550, 0.0000000000,
        0.0355942445, 0.0196749947, 0.0000000000,
        0.0356013262, 0.0196618541, 0.0000000000,
        0.0356060475, 0.0196530935, 0.0000000000
    )
$p2_7 = [double[]]@(
        0.0356060475, 0.0196530935, 0.0000000000,
        0.0356974305, 0.0194526040, 0.0000000000,
        0.0358435815, 0.0190268038, 0.0000000000,
        0.0360433801, 0.0182728057, 0.0000000000,
        0.0362206479, 0.0174926876, 0.0000000000,
        0.0367829630, 0.0150980933, 0.0000000000,
        0.0370850243, 0.0142085156, 0.0000000000,
        0.0373906413, 0.0136130282, 0.0000000000,
        0.0378683963, 0.0131043940, 0.0000000000,
        0.0388313132, 0.0126688752, 0.0000000000,
        0.0392515550, 0.0126068241, 0.0000000000,
        0.0402009281, 0.0126070791, 0.0000000000,
        0.0411202195, 0.0126428102, 0.0000000000,
        0.0417666449, 0.0125275568, 0.0000000000,
        0.0420959078, 0.0122870427, 0.0000000000,
        0.0422948122, 0.0120111723, 0.0000000000,
        0.0425592395, 0.0115632119, 0.0000000000,
        0.0432643289, 0.0107528572, 0.0000000000,
        0.0440427410, 0.0103491114, 0.0000000000,
        0.0450289730, 0.0101409190, 0.0000000000,
        0.0459161228, 0.0100690390, 0.0000000000,
        0.0465556793, 0.0100435446, 0.0000000000,
        0.0475955402, 0.0100300401, 0.0000000000,
        0.0501351215, 0.0100749059, 0.0000000000,
        0.0524329353, 0.0101744824, 0.0000000000,
        0.0539949860, 0.0102704273, 0.0000000000
    )
$p2_8 = [double[]]@(
        0.0539949860, 0.0102704273, 0.0000000000,
        0.0553456513, 0.0099639679, 0.0000000000,
        0.0564176617, 0.0097171141, 0.0000000000,
        0.0571820272, 0.0095383441, 0.0000000000,
        0.0583683000, 0.0092535151, 0.0000000000,
        0.0591199352, 0.0090646039, 0.0000000000,
        0.0598246455, 0.0088739664, 0.0000000000,
        0.0603488312, 0.0087076742, 0.0000000000,
        0.0608266781, 0.0085156896, 0.0000000000,
        0.0611883516, 0.0083120097, 0.0000000000,
        0.0613606854, 0.0081677082, 0.0000000000,
        0.0615756368, 0.0079578979, 0.0000000000,
        0.0618150424, 0.0078049594, 0.0000000000,
        0.0620560810, 0.0077726477, 0.0000000000,
        0.0623836332, 0.0079488295, 0.0000000000,
        0.0624999520, 0.0082626414, 0.0000000000,
        0.0624369351, 0.0085125703, 0.0000000000,
        0.0622202317, 0.0087225901, 0.0000000000
    )
$profile2 = New-Object 'double[][]' 9
$profile2[0] = $p2_0
$profile2[1] = $p2_1
$profile2[2] = $p2_2
$profile2[3] = $p2_3
$profile2[4] = $p2_4
$profile2[5] = $p2_5
$profile2[6] = $p2_6
$profile2[7] = $p2_7
$profile2[8] = $p2_8

$p3_0 = [double[]]@(
        0.0596103096, 0.0164276593, 0.0000000000,
        0.0596004504, 0.0164104797, 0.0000000000,
        0.0595905923, 0.0163933019, 0.0000000000,
        0.0595807353, 0.0163761259, 0.0000000000
    )
$p3_1 = [double[]]@(
        0.0595807353, 0.0163761259, 0.0000000000,
        0.0595017708, 0.0163236459, 0.0000000000,
        0.0593404546, 0.0162918408, 0.0000000000,
        0.0592148271, 0.0162817843, 0.0000000000,
        0.0588512756, 0.0163056684, 0.0000000000,
        0.0582460914, 0.0164145165, 0.0000000000,
        0.0574059593, 0.0166399044, 0.0000000000,
        0.0565111490, 0.0169283515, 0.0000000000,
        0.0547675118, 0.0175465245, 0.0000000000,
        0.0534509599, 0.0180077460, 0.0000000000,
        0.0527175827, 0.0182423828, 0.0000000000,
        0.0516101155, 0.0185312567, 0.0000000000,
        0.0509278949, 0.0186328133, 0.0000000000,
        0.0506233638, 0.0186433133, 0.0000000000,
        0.0504833412, 0.0186412860, 0.0000000000,
        0.0503198104, 0.0186196297, 0.0000000000,
        0.0501716854, 0.0185960679, 0.0000000000,
        0.0500148573, 0.0185448159, 0.0000000000,
        0.0499154290, 0.0185101707, 0.0000000000,
        0.0497570478, 0.0184245661, 0.0000000000,
        0.0496335882, 0.0183483985, 0.0000000000,
        0.0495169027, 0.0182464227, 0.0000000000,
        0.0494084999, 0.0181429632, 0.0000000000,
        0.0493132723, 0.0180203247, 0.0000000000,
        0.0492420789, 0.0179234200, 0.0000000000,
        0.0491716530, 0.0177967908, 0.0000000000,
        0.0490161972, 0.0174450719, 0.0000000000,
        0.0489090123, 0.0170388374, 0.0000000000,
        0.0488282704, 0.0164900111, 0.0000000000,
        0.0487895294, 0.0157962642, 0.0000000000,
        0.0487881367, 0.0148662903, 0.0000000000,
        0.0487824482, 0.0142862944, 0.0000000000,
        0.0487475770, 0.0138829822, 0.0000000000
    )
$p3_2 = [double[]]@(
        0.0487475770, 0.0138829822, 0.0000000000,
        0.0487301101, 0.0138775872, 0.0000000000,
        0.0486843207, 0.0139178309, 0.0000000000,
        0.0486205431, 0.0139738804, 0.0000000000,
        0.0485158664, 0.0140819555, 0.0000000000,
        0.0483145424, 0.0143109184, 0.0000000000,
        0.0478821088, 0.0148865019, 0.0000000000,
        0.0473105996, 0.0157313050, 0.0000000000,
        0.0464626138, 0.0170347303, 0.0000000000,
        0.0453199925, 0.0186880289, 0.0000000000,
        0.0440245402, 0.0202027455, 0.0000000000,
        0.0429784722, 0.0210191985, 0.0000000000,
        0.0423169949, 0.0213139794, 0.0000000000,
        0.0404819557, 0.0216138014, 0.0000000000,
        0.0380192177, 0.0215325364, 0.0000000000,
        0.0367812268, 0.0214626932, 0.0000000000,
        0.0357717949, 0.0214817882, 0.0000000000,
        0.0351714919, 0.0215861840, 0.0000000000,
        0.0348589261, 0.0217199290, 0.0000000000,
        0.0346730796, 0.0218796820, 0.0000000000
    )
$p3_3 = [double[]]@(
        0.0346730796, 0.0218796820, 0.0000000000,
        0.0346518016, 0.0219135451, 0.0000000000,
        0.0346307501, 0.0219475572, 0.0000000000,
        0.0346096985, 0.0219815694, 0.0000000000
    )
$p3_4 = [double[]]@(
        0.0346096985, 0.0219815694, 0.0000000000,
        0.0345550776, 0.0221266471, 0.0000000000,
        0.0344867435, 0.0225715270, 0.0000000000,
        0.0345181310, 0.0233850375, 0.0000000000,
        0.0347414498, 0.0247005960, 0.0000000000,
        0.0349237665, 0.0254589407, 0.0000000000,
        0.0352608901, 0.0266574296, 0.0000000000,
        0.0353910011, 0.0270830713, 0.0000000000,
        0.0354761372, 0.0273550556, 0.0000000000,
        0.0357588160, 0.0282358415, 0.0000000000,
        0.0359088082, 0.0287022805, 0.0000000000,
        0.0360437097, 0.0291472997, 0.0000000000,
        0.0361149027, 0.0294643876, 0.0000000000,
        0.0360890221, 0.0297470255, 0.0000000000,
        0.0359417258, 0.0299585908, 0.0000000000
    )
$p3_5 = [double[]]@(
        0.0359417258, 0.0299585908, 0.0000000000,
        0.0357723075, 0.0300554426, 0.0000000000,
        0.0355606226, 0.0300855663, 0.0000000000,
        0.0353382340, 0.0300148555, 0.0000000000,
        0.0351714565, 0.0298577225, 0.0000000000,
        0.0350088714, 0.0295264941, 0.0000000000,
        0.0348593746, 0.0290699459, 0.0000000000,
        0.0346982771, 0.0285127971, 0.0000000000,
        0.0344071317, 0.0274520457, 0.0000000000,
        0.0342651694, 0.0269310544, 0.0000000000,
        0.0340646131, 0.0262031368, 0.0000000000,
        0.0337742088, 0.0251837342, 0.0000000000,
        0.0334703828, 0.0241785666, 0.0000000000,
        0.0328867718, 0.0224973659, 0.0000000000,
        0.0326101879, 0.0218544709, 0.0000000000,
        0.0322957048, 0.0212861341, 0.0000000000,
        0.0321901460, 0.0211513051, 0.0000000000,
        0.0321173208, 0.0210835029, 0.0000000000
    )
$p3_6 = [double[]]@(
        0.0321173208, 0.0210835029, 0.0000000000,
        0.0320830731, 0.0210631039, 0.0000000000,
        0.0320458884, 0.0210460998, 0.0000000000,
        0.0320128572, 0.0210352527, 0.0000000000
    )
$p3_7 = [double[]]@(
        0.0320128572, 0.0210352527, 0.0000000000,
        0.0319929737, 0.0210330989, 0.0000000000,
        0.0319681193, 0.0210304066, 0.0000000000,
        0.0319482136, 0.0210286325, 0.0000000000
    )
$p3_8 = [double[]]@(
        0.0319482136, 0.0210286325, 0.0000000000,
        0.0316346305, 0.0211082532, 0.0000000000,
        0.0314054601, 0.0212313671, 0.0000000000,
        0.0310696128, 0.0214663694, 0.0000000000,
        0.0305765019, 0.0218973097, 0.0000000000,
        0.0297988145, 0.0227102907, 0.0000000000,
        0.0291897440, 0.0234064934, 0.0000000000,
        0.0288868913, 0.0237527786, 0.0000000000,
        0.0286090025, 0.0240541783, 0.0000000000,
        0.0283651017, 0.0242835999, 0.0000000000,
        0.0281479258, 0.0244140342, 0.0000000000,
        0.0277728235, 0.0243818274, 0.0000000000,
        0.0275388815, 0.0241297274, 0.0000000000,
        0.0275069215, 0.0238535151, 0.0000000000,
        0.0276141398, 0.0236184371, 0.0000000000,
        0.0277877537, 0.0234600605, 0.0000000000,
        0.0280917164, 0.0231419801, 0.0000000000,
        0.0288115015, 0.0223167506, 0.0000000000,
        0.0299154039, 0.0211456404, 0.0000000000,
        0.0304871507, 0.0206526027, 0.0000000000,
        0.0312255587, 0.0201951576, 0.0000000000,
        0.0317121696, 0.0200457050, 0.0000000000,
        0.0319613191, 0.0200265700, 0.0000000000,
        0.0320911899, 0.0200378985, 0.0000000000,
        0.0322150611, 0.0200531343, 0.0000000000,
        0.0323496181, 0.0200933057, 0.0000000000,
        0.0324723712, 0.0201361263, 0.0000000000,
        0.0326077872, 0.0202116597, 0.0000000000,
        0.0327220089, 0.0202835077, 0.0000000000,
        0.0328335160, 0.0203839951, 0.0000000000,
        0.0329343881, 0.0204810268, 0.0000000000,
        0.0330461041, 0.0206222242, 0.0000000000,
        0.0331190693, 0.0207175271, 0.0000000000,
        0.0333408845, 0.0210855813, 0.0000000000,
        0.0334399385, 0.0212707020, 0.0000000000,
        0.0334811070, 0.0213567830, 0.0000000000,
        0.0335471966, 0.0214969722, 0.0000000000,
        0.0335919670, 0.0215919391, 0.0000000000,
        0.0336163731, 0.0216468711, 0.0000000000,
        0.0336349322, 0.0216904661, 0.0000000000,
        0.0336502505, 0.0216918412, 0.0000000000
    )
$p3_9 = [double[]]@(
        0.0336502505, 0.0216918412, 0.0000000000,
        0.0337084779, 0.0215432543, 0.0000000000,
        0.0337848070, 0.0214142264, 0.0000000000,
        0.0338822631, 0.0212631563, 0.0000000000,
        0.0340053387, 0.0211312447, 0.0000000000,
        0.0340899647, 0.0210454499, 0.0000000000,
        0.0341855267, 0.0209730781, 0.0000000000,
        0.0343319922, 0.0208684090, 0.0000000000,
        0.0344556697, 0.0208028309, 0.0000000000,
        0.0345985516, 0.0207307808, 0.0000000000,
        0.0347392588, 0.0206788418, 0.0000000000,
        0.0348902208, 0.0206258948, 0.0000000000,
        0.0353591003, 0.0205251912, 0.0000000000,
        0.0360061773, 0.0204646534, 0.0000000000,
        0.0370259647, 0.0204720018, 0.0000000000,
        0.0399418009, 0.0206215455, 0.0000000000,
        0.0413764396, 0.0205201265, 0.0000000000,
        0.0419980841, 0.0203656796, 0.0000000000,
        0.0424815558, 0.0201505996, 0.0000000000,
        0.0428295769, 0.0199161517, 0.0000000000,
        0.0435535157, 0.0192567509, 0.0000000000,
        0.0445929283, 0.0179894356, 0.0000000000,
        0.0453925377, 0.0168403930, 0.0000000000,
        0.0460657944, 0.0158108206, 0.0000000000,
        0.0465240704, 0.0151069017, 0.0000000000,
        0.0468185493, 0.0146662644, 0.0000000000,
        0.0476416830, 0.0135595599, 0.0000000000,
        0.0483206204, 0.0129436928, 0.0000000000,
        0.0488199627, 0.0127773177, 0.0000000000,
        0.0492184638, 0.0128581023, 0.0000000000,
        0.0493929128, 0.0129739102, 0.0000000000,
        0.0494865665, 0.0130796564, 0.0000000000,
        0.0496473813, 0.0133664765, 0.0000000000,
        0.0497334333, 0.0137153915, 0.0000000000,
        0.0497852337, 0.0143931212, 0.0000000000,
        0.0498049199, 0.0161529254, 0.0000000000,
        0.0499989704, 0.0172109574, 0.0000000000,
        0.0500897791, 0.0173895412, 0.0000000000,
        0.0502279156, 0.0175410306, 0.0000000000
    )
$p3_10 = [double[]]@(
        0.0502279156, 0.0175410306, 0.0000000000,
        0.0502535163, 0.0175563112, 0.0000000000,
        0.0502791191, 0.0175715931, 0.0000000000,
        0.0503066102, 0.0175876431, 0.0000000000
    )
$p3_11 = [double[]]@(
        0.0503066102, 0.0175876431, 0.0000000000,
        0.0503395529, 0.0175989990, 0.0000000000,
        0.0503724936, 0.0176103543, 0.0000000000,
        0.0504054891, 0.0176214943, 0.0000000000
    )
$p3_12 = [double[]]@(
        0.0504054891, 0.0176214943, 0.0000000000,
        0.0505500077, 0.0176425096, 0.0000000000,
        0.0509992474, 0.0176227922, 0.0000000000,
        0.0517441718, 0.0174752664, 0.0000000000,
        0.0525619427, 0.0172438353, 0.0000000000,
        0.0531331030, 0.0170596080, 0.0000000000,
        0.0543177058, 0.0166453485, 0.0000000000,
        0.0559947934, 0.0160487650, 0.0000000000,
        0.0572412814, 0.0156460124, 0.0000000000,
        0.0584358826, 0.0153562036, 0.0000000000,
        0.0589068578, 0.0152924678, 0.0000000000,
        0.0590517145, 0.0152867049, 0.0000000000,
        0.0592366337, 0.0152811187, 0.0000000000,
        0.0593563134, 0.0152898084, 0.0000000000,
        0.0595503998, 0.0153072204, 0.0000000000,
        0.0597016740, 0.0153428991, 0.0000000000,
        0.0598230190, 0.0153738412, 0.0000000000,
        0.0599911658, 0.0154503547, 0.0000000000,
        0.0601273325, 0.0155241871, 0.0000000000,
        0.0602694463, 0.0156502707, 0.0000000000,
        0.0603968042, 0.0157909090, 0.0000000000,
        0.0604574111, 0.0158946795, 0.0000000000,
        0.0605315414, 0.0160305711, 0.0000000000,
        0.0605789423, 0.0161738207, 0.0000000000,
        0.0606240921, 0.0163273202, 0.0000000000,
        0.0606463846, 0.0164806669, 0.0000000000,
        0.0606656714, 0.0166294258, 0.0000000000,
        0.0606714848, 0.0169193667, 0.0000000000,
        0.0605620358, 0.0178320244, 0.0000000000,
        0.0603090450, 0.0188715373, 0.0000000000,
        0.0595453205, 0.0211673939, 0.0000000000,
        0.0590674971, 0.0225098720, 0.0000000000
    )
$p3_13 = [double[]]@(
        0.0590674971, 0.0225098720, 0.0000000000,
        0.0590627360, 0.0225240962, 0.0000000000,
        0.0590590127, 0.0225352137, 0.0000000000,
        0.0590759802, 0.0225474423, 0.0000000000
    )
$p3_14 = [double[]]@(
        0.0590759802, 0.0225474423, 0.0000000000,
        0.0595039131, 0.0220270978, 0.0000000000,
        0.0607137900, 0.0204346472, 0.0000000000,
        0.0613921107, 0.0195310699, 0.0000000000,
        0.0615484043, 0.0193355132, 0.0000000000,
        0.0616842226, 0.0191886744, 0.0000000000,
        0.0619398993, 0.0190799660, 0.0000000000,
        0.0620899276, 0.0190844946, 0.0000000000,
        0.0624269740, 0.0193161634, 0.0000000000,
        0.0624939103, 0.0196541329, 0.0000000000,
        0.0624292912, 0.0198326769, 0.0000000000,
        0.0623117245, 0.0199815344, 0.0000000000,
        0.0622238694, 0.0200906453, 0.0000000000,
        0.0620468515, 0.0203203819, 0.0000000000,
        0.0617648929, 0.0206964060, 0.0000000000,
        0.0609100964, 0.0218428362, 0.0000000000,
        0.0597961932, 0.0232436242, 0.0000000000,
        0.0592493394, 0.0238272025, 0.0000000000,
        0.0589821251, 0.0240532232, 0.0000000000,
        0.0587263196, 0.0242090825, 0.0000000000,
        0.0582563313, 0.0242579276, 0.0000000000,
        0.0578900525, 0.0239958723, 0.0000000000,
        0.0578126294, 0.0238112381, 0.0000000000,
        0.0579001567, 0.0228910613, 0.0000000000,
        0.0582215835, 0.0218967232, 0.0000000000,
        0.0587107877, 0.0205317508, 0.0000000000,
        0.0592166861, 0.0190349918, 0.0000000000,
        0.0594580033, 0.0181886146, 0.0000000000,
        0.0596312963, 0.0173365477, 0.0000000000,
        0.0596713306, 0.0169183245, 0.0000000000,
        0.0596451069, 0.0165392117, 0.0000000000,
        0.0596103096, 0.0164276593, 0.0000000000
    )
$profile3 = New-Object 'double[][]' 15
$profile3[0] = $p3_0
$profile3[1] = $p3_1
$profile3[2] = $p3_2
$profile3[3] = $p3_3
$profile3[4] = $p3_4
$profile3[5] = $p3_5
$profile3[6] = $p3_6
$profile3[7] = $p3_7
$profile3[8] = $p3_8
$profile3[9] = $p3_9
$profile3[10] = $p3_10
$profile3[11] = $p3_11
$profile3[12] = $p3_12
$profile3[13] = $p3_13
$profile3[14] = $p3_14

$p4_0 = [double[]]@(
        0.0560906276, 0.0206734037, 0.0000000000,
        0.0566075837, 0.0210975754, 0.0000000000,
        0.0573702171, 0.0217520048, 0.0000000000,
        0.0579477307, 0.0223268979, 0.0000000000,
        0.0582290814, 0.0226781165, 0.0000000000,
        0.0584008089, 0.0229769258, 0.0000000000,
        0.0584677079, 0.0231331169, 0.0000000000,
        0.0585008407, 0.0232640990, 0.0000000000,
        0.0585279138, 0.0234317124, 0.0000000000,
        0.0585248448, 0.0235469471, 0.0000000000,
        0.0585131195, 0.0236762132, 0.0000000000,
        0.0584619145, 0.0238283774, 0.0000000000,
        0.0584239527, 0.0239207020, 0.0000000000,
        0.0583128008, 0.0240745672, 0.0000000000,
        0.0581916972, 0.0242017180, 0.0000000000,
        0.0580674041, 0.0242852633, 0.0000000000,
        0.0579566995, 0.0243533924, 0.0000000000,
        0.0578141518, 0.0244143329, 0.0000000000,
        0.0575792410, 0.0244992335, 0.0000000000,
        0.0565699870, 0.0247244956, 0.0000000000,
        0.0563229586, 0.0247638235, 0.0000000000,
        0.0557028242, 0.0248426082, 0.0000000000,
        0.0545282538, 0.0249540117, 0.0000000000,
        0.0526716196, 0.0250665033, 0.0000000000,
        0.0502330289, 0.0251461669, 0.0000000000,
        0.0474532829, 0.0251742209, 0.0000000000,
        0.0463133365, 0.0251678207, 0.0000000000,
        0.0455684539, 0.0251560759, 0.0000000000,
        0.0451288048, 0.0251364176, 0.0000000000,
        0.0445897223, 0.0250555266, 0.0000000000,
        0.0442375499, 0.0249603630, 0.0000000000,
        0.0439228185, 0.0248454351, 0.0000000000
    )
$p4_1 = [double[]]@(
        0.0439228185, 0.0248454351, 0.0000000000,
        0.0439242613, 0.0248460064, 0.0000000000,
        0.0439315817, 0.0248489230, 0.0000000000,
        0.0439352609, 0.0248503853, 0.0000000000
    )
$p4_2 = [double[]]@(
        0.0439352609, 0.0248503853, 0.0000000000,
        0.0439229022, 0.0248715884, 0.0000000000,
        0.0439481056, 0.0249147694, 0.0000000000,
        0.0439985124, 0.0250011314, 0.0000000000,
        0.0440640413, 0.0251134019, 0.0000000000,
        0.0441451532, 0.0252514352, 0.0000000000,
        0.0442291697, 0.0253934239, 0.0000000000,
        0.0443542130, 0.0256040813, 0.0000000000,
        0.0446616239, 0.0261192701, 0.0000000000,
        0.0448766268, 0.0264800123, 0.0000000000,
        0.0451970217, 0.0270224918, 0.0000000000,
        0.0454627455, 0.0274811455, 0.0000000000,
        0.0460102259, 0.0284752925, 0.0000000000,
        0.0461319868, 0.0287107426, 0.0000000000,
        0.0463516397, 0.0291709166, 0.0000000000,
        0.0466037825, 0.0298020150, 0.0000000000,
        0.0467362900, 0.0305759957, 0.0000000000,
        0.0466990251, 0.0308024444, 0.0000000000,
        0.0463845061, 0.0312288180, 0.0000000000,
        0.0460614130, 0.0313462031, 0.0000000000,
        0.0455889319, 0.0313220920, 0.0000000000,
        0.0450130328, 0.0311568377, 0.0000000000,
        0.0444516055, 0.0309312264, 0.0000000000,
        0.0426223780, 0.0300179873, 0.0000000000,
        0.0417307040, 0.0295330802, 0.0000000000,
        0.0412405726, 0.0292622401, 0.0000000000,
        0.0401824351, 0.0286753972, 0.0000000000,
        0.0395424061, 0.0283243613, 0.0000000000,
        0.0388816504, 0.0279696203, 0.0000000000,
        0.0385976359, 0.0278221610, 0.0000000000,
        0.0383838283, 0.0277131920, 0.0000000000,
        0.0380971845, 0.0275707648, 0.0000000000,
        0.0378621289, 0.0274596688, 0.0000000000,
        0.0377438839, 0.0274054540, 0.0000000000,
        0.0376889338, 0.0273814576, 0.0000000000,
        0.0376751963, 0.0273754586, 0.0000000000,
        0.0376740102, 0.0273749388, 0.0000000000,
        0.0376729483, 0.0273744703, 0.0000000000,
        0.0376583527, 0.0273935370, 0.0000000000
    )
$p4_3 = [double[]]@(
        0.0376583527, 0.0273935370, 0.0000000000,
        0.0381813359, 0.0280016451, 0.0000000000,
        0.0390368128, 0.0290133962, 0.0000000000,
        0.0395018064, 0.0296332085, 0.0000000000,
        0.0398639955, 0.0302141211, 0.0000000000,
        0.0400493382, 0.0305970961, 0.0000000000,
        0.0401004302, 0.0307433540, 0.0000000000,
        0.0401504783, 0.0308953362, 0.0000000000,
        0.0401766279, 0.0310226746, 0.0000000000,
        0.0402059068, 0.0311800490, 0.0000000000,
        0.0402106768, 0.0313098999, 0.0000000000,
        0.0402123014, 0.0314650018, 0.0000000000,
        0.0401844171, 0.0316275469, 0.0000000000,
        0.0401513876, 0.0317735288, 0.0000000000,
        0.0400761553, 0.0319378396, 0.0000000000,
        0.0400100285, 0.0320623952, 0.0000000000,
        0.0399048089, 0.0321889452, 0.0000000000,
        0.0397810243, 0.0323196299, 0.0000000000,
        0.0396482441, 0.0324176120, 0.0000000000,
        0.0395040552, 0.0325167522, 0.0000000000,
        0.0393634127, 0.0325930805, 0.0000000000,
        0.0392310860, 0.0326636651, 0.0000000000,
        0.0390753080, 0.0327317675, 0.0000000000,
        0.0386986082, 0.0328799964, 0.0000000000,
        0.0374205937, 0.0332453664, 0.0000000000,
        0.0352110654, 0.0336692701, 0.0000000000,
        0.0334645834, 0.0339239438, 0.0000000000,
        0.0311823156, 0.0342079571, 0.0000000000,
        0.0298664499, 0.0343628545, 0.0000000000,
        0.0291865023, 0.0344458940, 0.0000000000,
        0.0287800061, 0.0344991206, 0.0000000000,
        0.0283198288, 0.0345659430, 0.0000000000,
        0.0280684411, 0.0346091368, 0.0000000000,
        0.0279082959, 0.0346053613, 0.0000000000,
        0.0276952739, 0.0345102538, 0.0000000000,
        0.0275720733, 0.0343724508, 0.0000000000,
        0.0275036269, 0.0341739505, 0.0000000000
    )
$p4_4 = [double[]]@(
        0.0275036269, 0.0341739505, 0.0000000000,
        0.0275110640, 0.0340092451, 0.0000000000,
        0.0275719794, 0.0338553906, 0.0000000000,
        0.0276919971, 0.0337199729, 0.0000000000,
        0.0278282704, 0.0336442595, 0.0000000000,
        0.0280135066, 0.0336040526, 0.0000000000,
        0.0282553638, 0.0335643490, 0.0000000000,
        0.0284631275, 0.0335331926, 0.0000000000,
        0.0289041916, 0.0334738766, 0.0000000000,
        0.0296931380, 0.0333764235, 0.0000000000,
        0.0311976847, 0.0331991695, 0.0000000000,
        0.0317189585, 0.0331368873, 0.0000000000,
        0.0324783230, 0.0330437109, 0.0000000000,
        0.0337818752, 0.0328712894, 0.0000000000,
        0.0352255452, 0.0326538547, 0.0000000000,
        0.0372227227, 0.0322643887, 0.0000000000,
        0.0385496575, 0.0318700094, 0.0000000000,
        0.0389947567, 0.0316554129, 0.0000000000,
        0.0391176483, 0.0315676605, 0.0000000000
    )
$p4_5 = [double[]]@(
        0.0391176483, 0.0315676605, 0.0000000000,
        0.0391346343, 0.0315492647, 0.0000000000,
        0.0391549000, 0.0315271464, 0.0000000000,
        0.0391717881, 0.0315087145, 0.0000000000
    )
$p4_6 = [double[]]@(
        0.0391717881, 0.0315087145, 0.0000000000,
        0.0391902900, 0.0314737342, 0.0000000000,
        0.0392041974, 0.0314295664, 0.0000000000,
        0.0392120957, 0.0313906301, 0.0000000000
    )
$p4_7 = [double[]]@(
        0.0392120957, 0.0313906301, 0.0000000000,
        0.0391817252, 0.0311473932, 0.0000000000,
        0.0389500342, 0.0306276952, 0.0000000000,
        0.0383175513, 0.0297161558, 0.0000000000,
        0.0372453481, 0.0284492927, 0.0000000000,
        0.0368431239, 0.0279772941, 0.0000000000,
        0.0364489104, 0.0274604839, 0.0000000000,
        0.0362558364, 0.0271166760, 0.0000000000,
        0.0362230879, 0.0270168301, 0.0000000000,
        0.0361898478, 0.0268898047, 0.0000000000,
        0.0361871503, 0.0267253221, 0.0000000000,
        0.0362122199, 0.0265674799, 0.0000000000,
        0.0363172281, 0.0263805475, 0.0000000000,
        0.0364102724, 0.0262760608, 0.0000000000,
        0.0366113981, 0.0261673113, 0.0000000000,
        0.0367647007, 0.0261227639, 0.0000000000,
        0.0368902923, 0.0261173316, 0.0000000000,
        0.0370202424, 0.0261185434, 0.0000000000,
        0.0372171509, 0.0261536255, 0.0000000000,
        0.0376800050, 0.0262963315, 0.0000000000,
        0.0383596505, 0.0265887544, 0.0000000000,
        0.0393249905, 0.0270728407, 0.0000000000,
        0.0407792358, 0.0278628190, 0.0000000000,
        0.0420779952, 0.0285827319, 0.0000000000,
        0.0438004461, 0.0295072339, 0.0000000000,
        0.0448586988, 0.0300178099, 0.0000000000,
        0.0456740336, 0.0303194198, 0.0000000000
    )
$p4_8 = [double[]]@(
        0.0456740336, 0.0303194198, 0.0000000000,
        0.0456839674, 0.0303215778, 0.0000000000,
        0.0456937442, 0.0303235063, 0.0000000000,
        0.0457004715, 0.0303248310, 0.0000000000
    )
$p4_9 = [double[]]@(
        0.0457004715, 0.0303248310, 0.0000000000,
        0.0457105982, 0.0303099785, 0.0000000000,
        0.0457009117, 0.0302713701, 0.0000000000,
        0.0456776432, 0.0301848605, 0.0000000000,
        0.0456101016, 0.0299857016, 0.0000000000,
        0.0455317057, 0.0297909815, 0.0000000000,
        0.0454311432, 0.0295622521, 0.0000000000,
        0.0452915668, 0.0292685519, 0.0000000000,
        0.0450259477, 0.0287529371, 0.0000000000,
        0.0444787469, 0.0277757411, 0.0000000000,
        0.0436074942, 0.0263044141, 0.0000000000,
        0.0432450404, 0.0256939306, 0.0000000000,
        0.0430335922, 0.0253309483, 0.0000000000,
        0.0426547519, 0.0246492229, 0.0000000000,
        0.0424204731, 0.0241738409, 0.0000000000,
        0.0422806588, 0.0238100733, 0.0000000000,
        0.0422170217, 0.0233855632, 0.0000000000,
        0.0422266426, 0.0231810571, 0.0000000000,
        0.0422849788, 0.0230216197, 0.0000000000,
        0.0425230813, 0.0227999002, 0.0000000000
    )
$p4_10 = [double[]]@(
        0.0425230813, 0.0227999002, 0.0000000000,
        0.0428366728, 0.0227677299, 0.0000000000,
        0.0429911400, 0.0228252264, 0.0000000000,
        0.0431029328, 0.0229094251, 0.0000000000,
        0.0433171816, 0.0231666699, 0.0000000000,
        0.0435890883, 0.0234598113, 0.0000000000,
        0.0438338836, 0.0236582879, 0.0000000000,
        0.0446062816, 0.0240286894, 0.0000000000,
        0.0449970638, 0.0241139600, 0.0000000000,
        0.0459951818, 0.0241636611, 0.0000000000,
        0.0472250736, 0.0241738546, 0.0000000000,
        0.0480400720, 0.0241731933, 0.0000000000,
        0.0495199470, 0.0241590424, 0.0000000000,
        0.0523886396, 0.0240780576, 0.0000000000,
        0.0545396727, 0.0239497002, 0.0000000000,
        0.0557787580, 0.0238276341, 0.0000000000,
        0.0563726588, 0.0237433460, 0.0000000000,
        0.0568744441, 0.0236520121, 0.0000000000,
        0.0573617564, 0.0235196180, 0.0000000000,
        0.0574952484, 0.0234637694, 0.0000000000
    )
$p4_11 = [double[]]@(
        0.0574952484, 0.0234637694, 0.0000000000,
        0.0575010747, 0.0234606502, 0.0000000000,
        0.0575094042, 0.0234552529, 0.0000000000,
        0.0575147447, 0.0234447022, 0.0000000000
    )
$p4_12 = [double[]]@(
        0.0575147447, 0.0234447022, 0.0000000000,
        0.0574035874, 0.0232435399, 0.0000000000,
        0.0570390499, 0.0228188679, 0.0000000000,
        0.0564753518, 0.0222944682, 0.0000000000,
        0.0552109336, 0.0212422714, 0.0000000000,
        0.0547052394, 0.0207876190, 0.0000000000,
        0.0544116035, 0.0204345074, 0.0000000000,
        0.0542952513, 0.0201418160, 0.0000000000,
        0.0543482912, 0.0197743152, 0.0000000000,
        0.0546169342, 0.0195038924, 0.0000000000,
        0.0548401504, 0.0194302739, 0.0000000000,
        0.0552247396, 0.0194247040, 0.0000000000,
        0.0558185062, 0.0195372965, 0.0000000000,
        0.0563002611, 0.0196719075, 0.0000000000,
        0.0577695137, 0.0201653416, 0.0000000000,
        0.0590223488, 0.0206116955, 0.0000000000,
        0.0604867031, 0.0211039572, 0.0000000000,
        0.0611175996, 0.0212804645, 0.0000000000,
        0.0614788518, 0.0213595228, 0.0000000000,
        0.0617817599, 0.0213936124, 0.0000000000,
        0.0619201971, 0.0213726102, 0.0000000000
    )
$p4_13 = [double[]]@(
        0.0619201971, 0.0213726102, 0.0000000000,
        0.0619479702, 0.0213257504, 0.0000000000,
        0.0619723356, 0.0211522462, 0.0000000000,
        0.0619007244, 0.0205677208, 0.0000000000,
        0.0615622644, 0.0193489948, 0.0000000000,
        0.0615147219, 0.0191239965, 0.0000000000,
        0.0615020613, 0.0189041575, 0.0000000000,
        0.0615829451, 0.0186737228, 0.0000000000,
        0.0616571072, 0.0185856208, 0.0000000000,
        0.0619892053, 0.0184496401, 0.0000000000,
        0.0623110693, 0.0185580708, 0.0000000000,
        0.0624736283, 0.0187892886, 0.0000000000,
        0.0625122090, 0.0190211524, 0.0000000000,
        0.0625698932, 0.0192437173, 0.0000000000,
        0.0626796139, 0.0196127443, 0.0000000000,
        0.0628563896, 0.0202588628, 0.0000000000,
        0.0629712541, 0.0211995810, 0.0000000000,
        0.0628309463, 0.0218047869, 0.0000000000,
        0.0624129547, 0.0222456818, 0.0000000000,
        0.0617765209, 0.0223944565, 0.0000000000,
        0.0616617041, 0.0223878342, 0.0000000000,
        0.0613838896, 0.0223563245, 0.0000000000,
        0.0605794048, 0.0221726879, 0.0000000000,
        0.0595671465, 0.0218582724, 0.0000000000,
        0.0588154281, 0.0215991564, 0.0000000000,
        0.0583866242, 0.0214471387, 0.0000000000,
        0.0575249863, 0.0211395300, 0.0000000000,
        0.0571193499, 0.0209966307, 0.0000000000,
        0.0568832348, 0.0209145034, 0.0000000000,
        0.0565515497, 0.0208021614, 0.0000000000,
        0.0563092832, 0.0207227323, 0.0000000000,
        0.0561566769, 0.0206746683, 0.0000000000,
        0.0560997920, 0.0206569106, 0.0000000000,
        0.0560906276, 0.0206734037, 0.0000000000
    )
$profile4 = New-Object 'double[][]' 14
$profile4[0] = $p4_0
$profile4[1] = $p4_1
$profile4[2] = $p4_2
$profile4[3] = $p4_3
$profile4[4] = $p4_4
$profile4[5] = $p4_5
$profile4[6] = $p4_6
$profile4[7] = $p4_7
$profile4[8] = $p4_8
$profile4[9] = $p4_9
$profile4[10] = $p4_10
$profile4[11] = $p4_11
$profile4[12] = $p4_12
$profile4[13] = $p4_13

$profiles = New-Object 'double[][][]' 5
$profiles[0] = $profile0
$profiles[1] = $profile1
$profiles[2] = $profile2
$profiles[3] = $profile3
$profiles[4] = $profile4
$tags  = [string[]]@('loop 0', 'loop 100', 'loop 200', 'loop 300', 'loop 400')
$names = [string[]]@('0', '100', '200', '300', '400')

$skirt = [double[]]@(
        0.0230000000, 0.0413950000, 0.0000000000,
        0.0230000000, 0.0439950000, 0.0000000000,
        0.0285000009, 0.0355728171, 0.0000000000,
        0.0285000009, 0.0340728171, 0.0000000000,
        0.0230000000, 0.0413950000, 0.0000000000
    )

# vent rings, flat: radius, diameter, count, phase
$rings = [double[]]@(
    0.0385044215, 0.0030000000, 8.0, 0.0000000000,
    0.0167250000, 0.0020000000, 6.0, 0.0000000000,
    0.0209750000, 0.0020000000, 6.0, 0.5235987756,
    0.0221500000, 0.0020000000, 6.0, 0.0000000000
)

[MultiSplineBuild]::BuildMerged(
    $profiles, $tags, $names,
    'Front Plane', 0.0255000014, 0.0649740881, 'Z:\cones-and-domes-paper\solidworks_export\bowl_amp_5spline_printable.SLDPRT',
    'Z:\JAXisymmetric\results\JAXdomeV2.SLDPRT', 0.0240000000, 0.1200000000, 0.1200000000,
    $skirt, $rings,
    7.25802373851e-07, 1e-09, 'Right Plane'
) | Out-Null
